#
# For full config options, check the docs:
#    docs.serverless.com


service: td-aws-asana
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  versionFunctions: false
  profile: asanatest
  memorySize: 256
  environment:
  REGION: ${opt:region, self:provider.region}
  package:
  exclude:
    - "awscli-bundle.zip"
    - "awscli-bundle/**"
    - "deploy-iterative-parse.sh"
    - "iterative-parse.json"
    - "events/**"

functions:
  namesToIDs:
    handler: handlers.namesToIDs
  parseTDAsanaRequest:
    handler: handlers.parseTaskRequest
  getAsanaTask:
    handler: handlers.getTask
  findAsanaTasks:
    handler: handlers.findTasks
  addAsanaTask:
    handler: handlers.addTask
  updateAsanaTask:
    handler: handlers.updateTask
  findProjectTag:
    handler: handlers.findProjectTag
  commentOnTask:
    handler: handlers.commentOnTask